FROM rabbitmq:3.9.7-management
## RUN rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_federation_management rabbitmq_stomp
LABEL version="1.0.0" maintainer="Maike Rodrigues <maikerodrigues@cialne.com.br>"