version: "3.5"
services:
  consumer:
    build:
      dockerfile: Dockerfile
      context: .
      target: build
    container_name: 'consumer-service'
    command: npm run start:dev
    ports:
        - 3002:3000
    volumes:
      - .:/home/node/app/:rw
    environment:
      APP_ENV: DEVELOPMENT
      APP_NAME: consumer-service
      RABBITMQ_URL: amqp://admin:admin@192.168.0.115:5672
      RABBITMQ_QUEUE: users
    networks:
        - consumer-network
networks:
  consumer-network:
    driver: bridge